name: Nop-Commerce-CI-CD

on:
  push:
    branches:
      - develop

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      #-------------------- CHECKOUT CODE --------------------
      - name: Checkout repository
        uses: actions/checkout@v4
